insert into albums (album_name, artist_name, release_date) values ('Kestrel''s Eye (Falkens öga)', 'Shay Chazelas', '11/19/1979');
insert into albums (album_name, artist_name, release_date) values ('Let No Man Write My Epitaph', 'Leeanne Currall', '8/28/1986');
insert into albums (album_name, artist_name, release_date) values ('Confessions of a Burning Man', 'Pru Prenty', '7/29/1971');
insert into albums (album_name, artist_name, release_date) values ('Saw IV', 'Nomi Skase', '8/8/1972');
insert into albums (album_name, artist_name, release_date) values ('Love Bites', 'Demetra Pococke', '7/27/1962');
insert into albums (album_name, artist_name, release_date) values ('Wolf Man, The', 'Johnath Parnham', '8/17/2020');
insert into albums (album_name, artist_name, release_date) values ('Between Two Worlds', 'Margo Corrie', '2/8/2022');
insert into albums (album_name, artist_name, release_date) values ('Sue', 'Niels Coltherd', '8/19/1981');
insert into albums (album_name, artist_name, release_date) values ('Gold Raiders', 'Roderich Dallender', '7/7/1969');
insert into albums (album_name, artist_name, release_date) values ('Road, Movie', 'Isabelle Bucham', '5/26/2006');
insert into albums (album_name, artist_name, release_date) values ('Submarine', 'Quinn Grinnikov', '3/14/1992');
insert into albums (album_name, artist_name, release_date) values ('Worlds Apart (To verdener)', 'Edithe Lenthall', '6/17/1983');
insert into albums (album_name, artist_name, release_date) values ('The Big Cube', 'Bent Lennie', '6/11/2021');
insert into albums (album_name, artist_name, release_date) values ('Room for One More', 'Vivia Morrad', '4/16/1982');
insert into albums (album_name, artist_name, release_date) values ('Suicide Manual (Jisatsu manyaru)', 'Fara Friedman', '9/7/1980');
insert into albums (album_name, artist_name, release_date) values ('Hôtel des Invalides', 'Carilyn Bellelli', '2/12/2002');
insert into albums (album_name, artist_name, release_date) values ('Reckoning, The', 'Baudoin Licas', '3/7/2001');
insert into albums (album_name, artist_name, release_date) values ('Face in the Crowd, A', 'Edmund Lukacs', '10/1/2006');
insert into albums (album_name, artist_name, release_date) values ('Light Years (Gandahar)', 'Denys Margaret', '5/20/1977');
insert into albums (album_name, artist_name, release_date) values ('Party Monster', 'Hesther Temblett', '7/29/1974');
