insert into songs (title, track_number, rating, album_id) values ('Hamiltons, The', 19, 1, 12);
insert into songs (title, track_number, rating, album_id) values ('Alexandria... Why? (Iskanderija... lih?)', 19, 2, 18);
insert into songs (title, track_number, rating, album_id) values ('Lady in Cement', 15, 2, 2);
insert into songs (title, track_number, rating, album_id) values ('Pelle Svanslös', 4, 4, 1);
insert into songs (title, track_number, rating, album_id) values ('Stepmom', 6, 4, 10);
insert into songs (title, track_number, rating, album_id) values ('Arsenic and Old Lace', 12, 4, 6);
insert into songs (title, track_number, rating, album_id) values ('Jack Frost', 19, 3, 14);
insert into songs (title, track_number, rating, album_id) values ('Hell Comes to Frogtown', 17, 4, 3);
insert into songs (title, track_number, rating, album_id) values ('Time That Remains, The', 10, 3, 13);
insert into songs (title, track_number, rating, album_id) values ('Infernal Affairs (Mou gaan dou)', 20, 3, 5);
insert into songs (title, track_number, rating, album_id) values ('Spice World', 6, 5, 2);
insert into songs (title, track_number, rating, album_id) values ('Tex', 14, 5, 1);
insert into songs (title, track_number, rating, album_id) values ('Hatchet III', 20, 5, 14);
insert into songs (title, track_number, rating, album_id) values ('Jackass 3D', 14, 4, 7);
insert into songs (title, track_number, rating, album_id) values ('After Life (Wandafuru raifu)', 2, 5, 16);
insert into songs (title, track_number, rating, album_id) values ('Bottle Shock', 7, 4, 2);
insert into songs (title, track_number, rating, album_id) values ('The Gamers: Hands of Fate', 5, 1, 14);
insert into songs (title, track_number, rating, album_id) values ('Taxidermia', 11, 1, 6);
insert into songs (title, track_number, rating, album_id) values ('Season of the Witch (Hungry Wives) (Jack''s Wife)', 8, 1, 12);
insert into songs (title, track_number, rating, album_id) values ('Trial', 9, 2, 11);
insert into songs (title, track_number, rating, album_id) values ('Painted Veil, The', 10, 4, 16);
insert into songs (title, track_number, rating, album_id) values ('Patriot, The', 7, 3, 17);
insert into songs (title, track_number, rating, album_id) values ('Nine Months', 1, 3, 1);
insert into songs (title, track_number, rating, album_id) values ('White: The Melody of the Curse', 9, 3, 6);
insert into songs (title, track_number, rating, album_id) values ('And When Did You Last See Your Father?', 17, 1, 9);
insert into songs (title, track_number, rating, album_id) values ('Empty Mirror, The', 20, 5, 15);
insert into songs (title, track_number, rating, album_id) values ('Everything I Can See From Here', 14, 4, 20);
insert into songs (title, track_number, rating, album_id) values ('Undisputed II: Last Man Standing', 9, 5, 19);
insert into songs (title, track_number, rating, album_id) values ('Iron & Silk', 14, 5, 3);
insert into songs (title, track_number, rating, album_id) values ('Gangsters', 8, 4, 3);
insert into songs (title, track_number, rating, album_id) values ('Bad Boys', 6, 3, 10);
insert into songs (title, track_number, rating, album_id) values ('Human Factor, The', 4, 2, 6);
insert into songs (title, track_number, rating, album_id) values ('Imagine: John Lennon', 10, 4, 17);
insert into songs (title, track_number, rating, album_id) values ('Warm Bodies', 11, 2, 10);
insert into songs (title, track_number, rating, album_id) values ('Black', 16, 4, 15);
insert into songs (title, track_number, rating, album_id) values ('Nowhere to Hide (Injeong sajeong bol geot eobtda)', 19, 2, 9);
insert into songs (title, track_number, rating, album_id) values ('Kilometre Zero (Kilomètre zéro)', 19, 2, 1);
insert into songs (title, track_number, rating, album_id) values ('Captain January', 16, 1, 14);
insert into songs (title, track_number, rating, album_id) values ('East of Eden', 18, 2, 13);
insert into songs (title, track_number, rating, album_id) values ('Topo, El', 19, 4, 18);
